version: "3.8"

services:
    redis:
        image: redis:alpine
        restart: always
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - daddy-net
    
    backend:
        image: paddyjoneill/daddynappychange
        restart: always
        ports: 
            - "5000:5000"
        expose:
            - "5000"
        networks:
            - daddy-net
        depends_on: 
            - redis
            - db
        command: gunicorn -b :5000 --access-logfile - dnc:app

    worker:
        image: paddyjoneill/daddynappychange
        restart: always
        command: celery -A dnc.celery worker --uid=1
        networks:
            - daddy-net
        depends_on: 
            - redis
            - db

    frontend:
        image: paddyjoneill/daddynappychangefrontend
        restart: always
        ports:
            # - "5001:80"
            - "80:80"
        networks:
            - daddy-net
        depends_on: 
            - backend


    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'innodb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        networks: 
            - daddy-net
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - /var/lib/mysql:/var/lib/mysql

    # reverse_proxy:
    #     image: caddy
    #     volumes:
    #         - ./Caddyfile:/etc/caddy/Caddyfile
    #         - ./.caddy:/root/.caddy
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     networks:
    #         - daddy-net
    #     depends_on: 
    #         - frontend
            

volumes:
    my-db:

networks:
    daddy-net: